### ISSUE TITLE
Copying Descriptors.c without attribution

### ISSUE THREAD

**Issue by wchill** [mfosse/switch-controller#1]
Hi,

I noticed that you copied and pasted my Descriptors.c into a detached fork (also wiping out the commit history) without attribution.

Please add attribution or remove it. The Horipad descriptors are not necessary for Switch control and Pokken pad descriptors are fine if that's all you care about.

**Comment by mfosse** [comment]
Sorry! I forgot about that! Is giving thanks in the readme enough or do you want me to state in the file where it came from? I'm not sure how I'd add git history.

I had the commit history but wiped it since I accidentally left in some sensitive data, (I would've removed just that commit, but I don't know how)

I was originally under the impression that the descriptors you made gave some advantage or additional functionality (like maybe the hori pad had a gyroscope that we could control?) So I copied it without thinking about it and forgot about it (is there a reason to use the horipad descriptiors over the pokken ones?)

I'll either remove it or change it later today when I get back home

**Comment by wchill** [comment]
There is no difference in functionality. The Horipad (https://www.amazon.com/Nintendo-Switch-HORIPAD-Controller-Officially-Licensed/dp/B01NAUATSM) has no gyro, vibration or NFC.

The only reason why I grabbed and used the Horipad descriptors is for accuracy. A name drop in the readme is fine.
